application: simblog
version: 1
runtime: python
api_version: 1

handlers:

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)
  
- url: /admin/.*
  script: blog.py 
  
- url: /.*
  script: main.py