application: srjsimblog
version: 1
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: static

- url: /myadmin/.*|/myadmin
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
  
- url: /admin/.*
  script: blog.py 

- url: /admin
  script: blog.py
    
- url: /.*
  script: main.py
  
