application: srjsimblog
version: 1
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: static

- url: /myadmin/.*|/myadmin
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
  
- url: /admin/.*
  script: blog.py 

- url: /admin
  script: blog.py

- url: /picture/.*
  script: picture.py 

- url: /picture
  script: picture.py
  
- url: /check_mail
  script: mailBlog.py
  
- url: /smtp2web_9e4648d8f6530a98.html
  static_files: smtp2web_9e4648d8f6530a98.html
  upload: smtp2web_9e4648d8f6530a98.html  
        
- url: /.*
  script: main.py



  
